# Device to run on (metal no longer maintained)
deviceType: cuda  # [cpu, cuda, metal]

# library mode
libMode: voxel  # [voxel, surfel]

# enables or disables loop closure (voxel mode only)
useLoopClosure: false

# create all the things required for marching cubes and mesh extraction - uses additional memory (lots!)
createMeshingEngine: false

# how swapping works: disabled, fully enabled (still with dragons) and delete what's not visible - not supported in loop closure version
swappingMode: disabled  # [disabled, enabled, delete]

# what to do on tracker failure: ignore, relocalise or stop integration - not supported in loop closure version
behaviourOnFailure: relocalise  # [ignore, relocalise, stopIntegration]

# enable or disable bilateral filtering of depth images
useBilateralFilter: false

# skips every other point when using the colour renderer for creating a point cloud
skipPoints: false

# enables or disables approximate raycast
useApproximateRaycast: false

voxelSceneParams:
  voxelSize: 0.005
  truncationDistance: 0.04
  maxWeight: 5000
  minDistance: 0.2
  maxDistance: 6.0
  stopIntegratingAtMaxWeight: false

surfelSceneParams:
  deltaRadius: 0.5
  gaussianConfidenceSigma: 0.6
  maxMergeAngle: 0.3490658503988659  # 20 * M_PI / 180
  maxMergeDist: 0.01
  maxSurfelRadius: 0.004
  minRadiusOverlapFactor: 3.5
  stableSurfelConfidence: 25.0
  supersamplingFactor: 4
  trackingSurfelMaxDepth: 1.0
  trackingSurfelMinConfidence: 5.0
  unstableSurfelPeriod: 20
  unstableSurfelZOffset: 10000000
  useGaussianSampleConfidence: true
  useSurfelMerging: true

fusionParams:
  tsdfMode: directional  # [directional, default]
  fusionMode: voxelProjection  # [voxelProjection, rayCastingNormal, rayCastingViewDirAndNormal, rayCastingViewDir]
  carvingMode: voxelProjection  # [voxelProjection, rayCasting]
  fusionMetric: pointToPoint  # [pointToPoint, pointToPlane]
  useWeighting: true
  useSpaceCarving: true

# Defautl ICP tracking:
voxelTrackerConfig: "type=icp,levels=rrbb,minstep=1e-5,
  outlierC=0.1,outlierF=0.004,
  numiterC=20,numiterF=50,failureDec=20.0" # 5 for normal, 20 for loop closure

## Depth-only extended tracking:
#voxelTrackerConfig: "type=extended,levels=rrbb,useDepth=1,minstep=1e-4,
#  outlierSpaceC=0.1,outlierSpaceF=0.004,
#  numiterC=20,numiterF=50,tukeyCutOff=8,
#  framesToSkip=1,framesToWeight=1,failureDec=20.0"

## For hybrid intensity+depth tracking:
#voxelTrackerConfig: "type=extended,levels=bbb,useDepth=1,useColour=1,
#  colourWeight=0.3,minstep=1e-4,
#  outlierColourC=0.175,outlierColourF=0.005,
#  outlierSpaceC=0.1,outlierSpaceF=0.004,
#  numiterC=20,numiterF=50,tukeyCutOff=8,
#  framesToSkip=20,framesToWeight=50,failureDec=20.0"

## Colour only tracking, using rendered colours
#voxelTrackerConfig: "type=rgb,levels=rrbb"

## IMU tracking
#voxelTrackerConfig: "type=imuicp,levels=tb,minstep=1e-3,outlierC=0.01,
#  outlierF=0.005,numiterC=4,numiterF=2"
#voxelTrackerConfig: "type=extendedimu,levels=ttb,minstep=5e-4,outlierSpaceC=0.1,
#  outlierSpaceF=0.004,numiterC=20,numiterF=5,tukeyCutOff=8,framesToSkip=20,
#  framesToWeight=50,failureDec=20.0"


surfelTrackerConfig: "extended,levels=rrbb,minstep=1e-4,
  outlierSpaceC=0.1,outlierSpaceF=0.004,numiterC=20,
  numiterF=20,tukeyCutOff=8,framesToSkip=0,framesToWeight=1,
  failureDec=20.0"
